agenda/urls.py
from django.conf.urls         import url
from .                        import views, models
from el_pagination.views      import AjaxListView
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(
        regex = r'^$',
        view  = AjaxListView.as_view(model = models.Event),
        name  = 'list',
    ),
    url(
        regex = _(r'^(?P<event_id>[0-9]+)/comments$'),
        view  = views.CommentAjaxListView.as_view(),
        name  = 'comment_list',
    ),
    url(
        regex = _(r'^event$'),
        view  = views.CreateEventView.as_view(),
        name  = 'event',
    ),
    url(
        regex = _(r'^event/(?P<pk>[\d]+)$'),
        view  = views.UpdateEventView.as_view(),
        name  = 'event',
    ),
    url(
        regex = _(r'^comment$'),
        view  = views.post_comment,
        name  = 'comment',
    ),
    url(
        regex = _(r'^participations$'),
        view  = views.participate,
        name  = 'participate',
    ),
    url(
        regex = _(r'^ics$'),
        view  = views.ics_export,
        name  = 'ics_export',
    ),
    url(
        regex = _(r'^event/update/(?P<event_id>[0-9]+)$'),
        view  = views.update_event,
        name  = 'update_event',
    ),
]

core/urls.py
from django.conf.urls         import url
from django.views.generic     import TemplateView
from django.utils.translation import ugettext_lazy as _
from .                        import views

urlpatterns = [
    url(r'^$',           views.home,                                      name = 'home'),
    url(_(r'^hq$'),      TemplateView.as_view(template_name = 'hq.html'), name = 'hq'),
    url(_(r'^map$'),     views.map,                                       name = 'map'),
    url(_(r'^friends$'), views.friends,                                   name = 'friends'),
]

sugarcub/urls.py
from django.conf.urls         import include, url, i18n
from django.contrib           import admin
from django.conf              import settings
from django.conf.urls.static  import static
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth      import views as auth_views
from users.forms              import AuthenticationForm


urls = [
    url(r'^captcha/', include('captcha.urls')),
    url(_(r'admin/doc/'), include('django.contrib.admindocs.urls')),
    url(_(r'admin/'),     include(admin.site.urls)),

    url(_(r'bbbff/'),     include('bbbff.urls',  namespace='bbbff')),
    url(_(r'agenda/'),    include('agenda.urls', namespace='agenda')),
    url(r'',              include('users.urls',  namespace='users')),
    url(r'',              include('core.urls',   namespace='core')),

    url(r'^login/$',
        auth_views.login,
        {
            'template_name': 'registration/login.html',
            'authentication_form': AuthenticationForm
        },
        name='auth_login'),
    url(r'',              include('registration.backends.default.urls')),
]


urlpatterns = i18n.i18n_patterns(*urls)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agenda/models.py
from   django.db                  import models
from   django.contrib.auth.models import User
from   django.core.urlresolvers   import reverse
from   django.utils.translation   import ugettext_lazy as _
import ics


information_enabled = (
    ('1', _('Show both my phone and my mail')),
    ('2', _('Show only my mail')),
    ('3', _('Show only my phone')),
)


class Event(models.Model):
    ''' Represent an event in the agenda '''

    author        = models.ForeignKey(User, verbose_name = _('user'))

    title         = models.CharField(_('title'), max_length = 500)
    description   = models.TextField(_('description'))
    date_begin    = models.DateTimeField(_('date begin'))
    date_end      = models.DateTimeField(_('date end'))
    address       = models.CharField(_('address'), max_length = 200)
    event_enabled = models.CharField(_('event enabled'), max_length = 10, choices = information_enabled)

    class Meta:
        ordering            = ['-date_begin', '-date_end']
        verbose_name        = _('event')
        verbose_name_plural = _('events')

    def get_absolute_url(self):
        return reverse('event', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    def __init__(self, *args, ics_import = None, **kwargs):
        super().__init__(*args, **kwargs)
        if ics_import is not None:
            self.from_ics_event(ics_import)

    def from_ics_event(self, ics_event):
        self.title       = ics_event.name
        self.date_begin  = ics_event.begin.naive
        self.date_end    = ics_event.end.naive
        self.description = ics_event.description

    def to_ics_event(self):
        return ics.Event(
            name        = self.title,
            begin       = self.date_begin,
            end         = self.date_end,
            description = self.description,
        )


class Comment(models.Model):
    '''
    Represent a post in a discussion attached to an event

    Comment is posted by author if logged in, else by pseudo
    '''

    author = models.ForeignKey(User, verbose_name = _('user'), blank = True, null = True)
    pseudo = models.CharField(_('unregistered user'), max_length = 30, blank = True, null = True)
    event  = models.ForeignKey(Event, verbose_name = _('event'))

    text   = models.TextField(_('text'))
    date   = models.DateTimeField(_('date'), auto_now_add = True)

    class Meta:
        ordering            = ['-date']
        verbose_name        = _('comment')
        verbose_name_plural = _('comments')

    def __str__(self):
        return self.text


class Participation(models.Model):
    '''
    Represent a participation to an event by a user

    Participation is made by author if logged in, else by pseudo
    '''

    user    = models.ForeignKey(User, verbose_name = _('user'), null = True, blank = True)
    pseudo  = models.CharField(_('unregistered user'), max_length = 31, blank = True, null=True)
    contact = models.CharField(_('contact'), max_length = 31, blank = True, null = True)
    event   = models.ForeignKey(Event, verbose_name = _('event'))

    class Meta:
        ordering            = ['pseudo']
        verbose_name        = _('participation')
        verbose_name_plural = _('participations')
        unique_together     = (
            ('user', 'event'),
            ('pseudo', 'event'),
        )

    def __str__(self):
        return str(self.author()) + ' ' + str(self.event)

    def author(self):
        return self.user if self.user else self.pseudo

agenda/forms.py
from django                      import forms
from .                           import models
from bootstrap3_datetime.widgets import DateTimePicker
from django.utils.translation    import ugettext_lazy as _
from captcha.fields              import CaptchaField


class EventForm(forms.ModelForm):

    date_begin = forms.DateTimeField(
        widget = DateTimePicker(
            options = {
                'format': 'DD/MM/YYYY HH:mm',
                'inline': True,
            }
        ),
        label = _('Start date and hour')
    )
    date_end = forms.DateTimeField(
        widget = DateTimePicker(
            options = {
                'format': 'DD/MM/YYYY HH:mm',
                'inline': True,
            }
        ),
        label = _('End date and hour')
    )

    class Meta:
        model  = models.Event
        exclude = ['author']
        labels = {
            'title':         _('Title'),
            'description':   _('Description'),
            'address':       _('Address of the event'),
            'event_enabled': _('Means of contact')
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update({'placeholder':
            _('Explain the event, add as much information you can : time, localisation '
                ', if people need stuff... the more information the better!')
        })


class CommentForm(forms.ModelForm):

    captcha = CaptchaField()

    class Meta:
        model  = models.Comment
        fields = ['text', 'pseudo']
        labels = {
            'text': _('Add a comment about the event...')
        }


class ParticipationForm(forms.ModelForm):

    captcha = CaptchaField()

    class Meta:
        model = models.Participation
        fields = ['pseudo', 'contact']

agenda/views.py
from django.shortcuts               import render
from django.core.urlresolvers       import reverse_lazy
from django.views.generic.edit      import CreateView, UpdateView
from .                              import models, forms, utils
from .forms                         import EventForm, CommentForm, ParticipationForm
from el_pagination.views            import AjaxListView
from django.http                    import HttpResponse
from django.shortcuts               import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators        import method_decorator
import json


class CommentAjaxListView(AjaxListView):

    form_class = forms.CommentForm

    def get_queryset(self):
        return models.Comment.objects.filter(event = self.kwargs['event_id'])


class CreateEventView(CreateView):

    form_class    = forms.EventForm
    success_url   = reverse_lazy('agenda:list')
    template_name = 'agenda/event_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        instance = form.save(commit = False)
        instance.author = self.request.user
        instance.save()
        utils.send_admin_event_notification.delay(instance.id)
        return super().form_valid(form)


class UpdateEventView(UpdateView):

    model         = models.Event
    form_class    = forms.EventForm
    success_url   = reverse_lazy('agenda:list')
    template_name = 'agenda/event_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


def post_comment(request):

    if request.POST:
        captcha = CommentForm(request.POST)
        if request.user.is_authenticated():
            event = models.Event.objects.get(pk = request.POST.get('event'))
            comment = models.Comment(
                author = request.user,
                text = request.POST.get('text'),
                event = event
            )
            comment.save()

        else:
            if captcha.is_valid():
                event = models.Event.objects.get(pk = request.POST.get('event'))
                comment = models.Comment(
                    pseudo = request.POST.get('pseudo'),
                    text = request.POST.get('text'),
                    event = event
                )
                comment.save()
            else:
                return HttpResponse(json.dumps(captcha.errors), status=400)

        return HttpResponse('success')


def participate(request):

    if request.method == 'POST':
        captcha = ParticipationForm(request.POST)
        if request.user.is_authenticated():
            event = models.Event.objects.get(pk = request.POST.get('event'))
            participation = models.Participation(
                user = request.user,
                event = event
            )
            try:
                participation.save()
            except:
                return HttpResponse(json.dumps(captcha.errors), status=400)

        else:
            if captcha.is_valid():
                event = models.Event.objects.get(pk = request.POST.get('event'))
                participation = models.Participation(
                    pseudo = request.POST.get('pseudo'),
                    event = event,
                    contact = request.POST.get('contact'),
                )
                try:
                    participation.save()
                except:
                    return HttpResponse(json.dumps(captcha.errors), status=400)

        return HttpResponse('success')

    return redirect('agenda:list')


def ics_export(request):
    calendar = str(utils.export_calendar())
    response = HttpResponse(calendar, content_type = 'text/calendar; charset=utf-8')
    response['Content-Disposition'] = 'attachment; filename=agenda.ics'
    response['Content-Lenght'] = len(calendar)
    return response


def update_event(request, event_id):
    try:
        event = models.Event.objects.get(id = event_id)
    except:
        return redirect('agenda:list')

    if event.author.id == request.user.id:
        if request.method == 'POST':

            form = EventForm(request.POST, request.FILES, instance = event)

            if form.is_valid():
                form.save()

                return redirect('agenda:list')

        else:
            form = EventForm(instance = event)

        return render(request, 'agenda/event_update_form.html', {
            'event':   event,
            'form':    form,
        })

    else:
        return redirect('agenda:list')

agenda/templates/agenda/comment_list.html
{% extends 'base.html' %}

{% load i18n %}
{% load el_pagination_tags %}

{% block title %}{% trans 'Events' %}{% endblock %}

{% block body %}
{{ block.super }}

<div class="container">
    <div class="row">
        <div class="col-xs-12 endless_page_template">
            {% include 'agenda/comment_list_page.html' %}
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}el_pagination/js/endless-pagination.js"></script>
    <script>$.endlessPaginate();</script>
{% endblock %}

agenda/templates/agenda/comment_list_page.html
{% load static %}

{% load i18n %}
{% load el_pagination_tags %}

{% url 'agenda:comment_list' comment_list.0.event.id as comment_url %}
{% lazy_paginate 3,10 comment_list with comment_url %}

{% for comment in comment_list %}
    <div class="comment panel panel-default">
        <div class="panel-heading">
            <img class="img-header thumbnail" alt="avatar" src="
                {% if comment.author.profile.avatar.small %}
                    {{ comment.author.profile.avatar.small.url }}
                {% else %}
                    {% static 'ressources/logo/icon_bronycub.png' %}
                {% endif %}
            "/>
            {% if comment.author == null %}
                {{ comment.pseudo }}
            {% else %}
                {{ comment.author }}
            {% endif %} 
        </div>
        <div class="panel-body">
            {{ comment.text }}
        </div>
    </div>
{% endfor %}
{% show_more 'more comments' %}

agenda/templates/agenda/event_list.html
{% extends 'base.html' %}

{% load i18n %}
{% load el_pagination_tags %}
{% load static %}
{% load absolute %}

{% block title %}{% trans 'Events' %}{% endblock %}

{% block body %}
{{ block.super }}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <a data-toggle="modal" data-target="#modal" class="btn btn-primary"><i class="fa fa-calendar-plus-o">&nbsp;</i>{% trans 'Add to your agenda' %}</a>
            <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="plusinfos" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title"><i class="fa fa-calendar-plus">&nbsp;</i>{% trans 'Add to your agenda' %}</h4>
                        </div>
                        <div class="modal-body">
                            <p><strong>{% trans 'To add the agenda in your favorite software use the address:' %}</strong></p>
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-link"></i></span>
                              <input type="text" class="form-control" value="{% absolute 'agenda:ics_export' %}">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if user.is_authenticated and user.profile.enabled %}
            <div class="col-md-6 text-right">
                <a class="btn btn-success" href="{% url 'agenda:event' %}"><strong><i class="fa fa-star"></i>&nbsp;{% trans 'Add an event' %}&nbsp;<i class="fa fa-star"></i></strong></a>
            </div>
        {% endif %}
        <div class="col-xs-12">
            <hr/>
            <div class="endless_page_template" id="event_list">
                {% include 'agenda/event_list_page.html' %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}el_pagination/js/endless-pagination.js"></script>
    <script>$.endlessPaginate();</script>
    {% if user.is_authenticated and user.profile.enabled %}
        <script>
            $(document).ready(function() {
                submitComment = function(id) {
                    var comment = $('#id_'+id+'_comment-text').val();
                    $.ajax({
                        type: 'post',
                        url:  '{% url 'agenda:comment' %}',
                        data:  {event: id, text: comment},
                        success: function() {
                            $('#comment-' + id).val('');
                            $('#comment-list-' + id).prepend(
                                '<div class="comment panel panel-default">' +
                                    '<div class="panel-heading">' +
                                        '<img class="img-header thumbnail" alt="avatar" src="' +
                                            {% if user.profile.avatar.small %}
                                                '{{ user.profile.avatar.small.url }}' +
                                            {% else %}
                                                '{% static 'ressources/logo/icon_bronycub.png' %}' +
                                            {% endif %}
                                        '"/>' +
                                        '{{ user.username }}' +
                                    '</div>' +
                                    '<div class="panel-body">' +
                                        comment +
                                    '</div>' +
                                '</div>'
                            );
                        }
                    });
                };
                submitParticipation = function(id) {
                    $.ajax({
                        type: 'post',
                        url:  '{% url 'agenda:participate' %}',
                        data:  {event: id},
                        success: function() {
                            $('#participation-list-' + id).prepend(
                                '<a data-toggle="modal" data-target="#modal-{{participant.user.username}}" class="member-link">' +
                                    '<div class="col-md-4">' +
                                        '<img class="img-responsive thumbnail" alt="avatar" src="' +
                                            {% if user.profile.avatar.small %}
                                                '{{ user.profile.avatar.small.url }}' +
                                            {% else %}
                                                '{% static 'ressources/logo/icon_bronycub.png' %}' +
                                            {% endif %}
                                        '"/>' +
                                    '</div>' +
                                '</a>'
                            );
                        },
                        error: function() {
                            alert('{% trans 'Erreur : Vous participez déjà à cet évènement!' %}');
                        }
                    });
                };
            });
        </script>
    {% else %}
        <script>
            $(document).ready(function() {
                submitComment_offline = function(id) {
                    var username_post = $('#id_'+id+'_comment-pseudo').val();
                    var comment = $('#id_'+id+'_comment-text').val();
                    var captcha_0 = $('#id_'+id+'_comment-captcha_0').val();
                    var captcha_1 = $('#id_'+id+'_comment-captcha_1').val();
                    $.ajax({
                        type: 'post',
                        url:  '{% url 'agenda:comment' %}',
                        data:  {event: id, text: comment, pseudo: username_post, captcha_0: captcha_0,captcha_1: captcha_1},
                        success: function() {
                            $('#comment-' + id).val('');
                            $('#comment-list-' + id).prepend(
                                '<div class="comment panel panel-default">' +
                                    '<div class="panel-heading">' +
                                        '<img class="img-header thumbnail" alt="avatar" src="' +
                                                '{% static 'ressources/logo/icon_bronycub.png' %}' +
                                        '"/>' +
                                        username_post +
                                    '</div>' +
                                    '<div class="panel-body">' +
                                        comment +
                                    '</div>' +
                                '</div>'
                            );
                        }
                    });
                };
                submitParticipation_offline = function(id) {
                    var username_post = $('#id_'+id+'_participation-pseudo').val();
                    var contact_post = $('#id_'+id+'_participation-contact').val();
                    var captcha_0 = $('#id_'+id+'_participation-captcha_0').val();
                    var captcha_1 = $('#id_'+id+'_participation-captcha_1').val();
                    console.log(username_post);
                    $.ajax({
                        type: 'post',
                        url:  '{% url 'agenda:participate' %}',
                        data:  {event: id, pseudo: username_post, contact: contact_post, captcha_0: captcha_0,captcha_1: captcha_1},
                        success: function() {
                            $('#participation-list-' + id).prepend(
                                '<a data-toggle="modal" data-target="#modal-{{participant.user.username}}" class="member-link">' +
                                    '<div class="col-md-4">' +
                                        '<img class="img-responsive thumbnail" alt="avatar" src="' +
                                                '{% static 'ressources/logo/icon_bronycub.png' %}' +
                                        '"/>' +
                                    '</div>' +
                                '</a>'                      
                            );
                        },
                        error: function() {
                            alert("{% trans "Erreur : Vous participez déjà à cet évènement! Si ce n'est pas vous, quelqu'un à déjà pris ce pseudo!" %}");
                        }
                    });
                };
            });
        </script>
    {% endif %}
{% endblock %}

agenda/templates/agenda/event_list_page.html
{% load static %}

{% load i18n %}
{% load el_pagination_tags %}
{% load comment_field %}
{% load participation_field %}
{% load agenda_extra %}

{% url 'agenda:list' as event_url %}
{% lazy_paginate event_list with event_url %}
{% for event in event_list %}
 <div class="event list-group" role="tablist" aria-multiselectable="true">
        <div class="list-group-item" role="tab" id="headingOne">
            <div class="list-group-item-heading">
                <a class="no_blue" data-toggle="collapse" data-parent="#event_list" href="#{{event.id}}" aria-expanded="false" aria-controls="collapseOne">
                    <h4><span class="label label-{% if event.date_end|hours_ago:1 %}default{% else %}primary{% endif %}">{{ event.date_begin|date }}</span> <i class="fa fa-caret-right"></i> <strong>{{ event.title }}</strong></h4>
                </a>
            </div>
            <div id="{{event.id}}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="row">
                    <div class="col-md-9">
                        <div>
                          <strong>{% trans 'From' %}
                          <p class="text-danger">{{ event.date_begin|date }} {% trans 'At' %} {{ event.date_begin|time }}</p>
                          {% trans 'To' %}
                          <p class="text-danger">{{ event.date_end|date }} {% trans 'At' %} {{ event.date_end|time }}</p></strong>
                          <strong>{% trans 'Address' %}
                          <p class="text-info">{{event.address}}</p>
                          </strong>
                          <br />
                          <blockquote>
                            <p style="word-wrap: break-word;"> {{ event.description }} </p>
                          </blockquote>
                        </div>
                      <hr />
                        {% with ''|addstr:event.id|addstr:'_comment' as eventId %}
                          {% comment_form prefix=eventId %}
                        {% endwith %}

                      <hr/>
                      <div id="comment-list-{{ event.id }}" class="list-group-item-text">
                          {% include 'agenda/comment_list_page.html' with comment_list=event.comment_set.all %}
                      </div>
                    </div>
                    <div class="col-md-3">
                      {% if user.is_authenticated and user.profile.enabled and event.author == user %}
                        <div class="panel panel-default">
                          <a href="{% url 'agenda:update_event' event_id=event.id %}" class="btn btn-primary btn-lg btn-block panel-body">{% trans 'Edit event' %}</a>
                        </div>
                      {% endif %}
                      <div class="panel panel-default">
                        <div class="panel-heading" style="text-align:left;">
                          <h3 class="panel-title"><strong>{% trans 'Will you participate?' %}</strong></h3>
                        </div>
                        <div class="panel-body" style="text-align:center;">
                          {% with ''|addstr:event.id|addstr:'_participation' as eventId %}
                            {% participation_form prefix=eventId %}
                          {% endwith %}
                        </div>
                      </div>
                          {% include 'agenda/participation_list_page.html' with participation_list=event.participation_set.all %}
                      <div class="panel panel-default">
                        <div class="panel-heading" style="text-align:left;">
                          <h3 class="panel-title"><strong>{% trans 'Organizer' %}</strong></h3>
                        </div>
                        <div class="panel-body" style="text-align:center;">
                          <img class="img-rounded thumbnail img-responsive" width="222px" src="{% if event.author.profile.avatar.big %}
                                 {{ event.author.profile.avatar.avatar.url }}
                             {% else %}
                                 {% static 'ressources/logo/icon_bronycub.png' %}
                             {% endif %}">
                          <h3>{{ event.author.username }}</h3>
                          <br />
                          <h4><strong><i class="fa fa-comments"></i>&nbsp;{% trans 'CONTACT' %}</strong></h4>
                          {% ifequal event.event_enabled "1"  %}
                            <p>{{ event.author.profile.phone }}</p>
                            <p>{{ event.author.email }}</p>
                          {% endifequal %}
                          {% ifequal event.event_enabled "2"  %}
                            <p>{{ event.author.email }}</p>
                          {% endifequal %}
                          {% ifequal event.event_enabled "3"  %}
                            <p>{{ event.author.profile.phone }}</p>
                          {% endifequal %}
                        </div>
                      </div>
                    </div>
                </div>
            <hr />
        </div>
    </div>
</div>
{% endfor %}
{% show_more 'more events' %}

agenda/templates/agenda/participation_list_page.html
{% load static %}

{% load i18n %}
{% load el_pagination_tags %}

<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><strong>{% trans 'Participant' %} : {{ participation_list.count }}</strong></h3>
    </div>
    <div id="participation-list-{{ event.id }}" class="panel-body">
    {% for participant in participation_list %}
        {% if participant.user == null %}
            <div id="modal-{{participant.pseudo}}" class="modal fade" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="container-fluid modal-content modal-lg">
                        <h4>Pseudo : {{ participant.pseudo }}</h4>
                    </div>
                    {% if user.is_authenticated and user.profile.enabled and event.author == user %}
                    <div class="container-fluid modal-content modal-lg">
                        <h4>Contact : {{ participant.contact }}</h4>
                    </div>
                    {% endif %}
                </div>
            </div>
            <a data-toggle="modal" data-target="#modal-{{participant.pseudo}}" class="member-link">
                <div class="col-md-4">
                    <img class="img-responsive thumbnail" alt="avatar" src="
                        {% if participant.user.profile.avatar.small %}
                            {{ participant.user.profile.avatar.small.url }}
                        {% else %}
                            {% static 'ressources/logo/icon_bronycub.png' %}
                        {% endif %}
                    "/>
                </div>
            </a>
        {% else %}
            <a data-toggle="modal" data-target="#modal-{{participant.user.username}}" class="member-link">
                <div class="col-md-4">
                    <img class="img-responsive thumbnail" alt="avatar" src="
                        {% if participant.user.profile.avatar.small %}
                            {{ participant.user.profile.avatar.small.url }}
                        {% else %}
                            {% static 'ressources/logo/icon_bronycub.png' %}
                        {% endif %}
                    "/>
                </div>
            </a>
            {% include '../../users/templates/members/one-user-modal.html' with profile=participant.user.profile %}
        {% endif %}
    {% endfor %}
    </div>
</div>
{% show_more 'more comments' %}